name: Build and Deploy

on: [push,pull_request]

jobs:
  build:
    name: Build, Test, Lint, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.5 

      - name: Install golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Lint with golangci-lint
        run: golangci-lint run ./...

      - name: Run tests
        run: go test ./...

      - name: Build Docker image
        run: docker build -t floppax/test_assigment:latest .

      - name: Log in to Docker Hub
        run: docker login -u floppax -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: docker push floppax/test_assigment:latest
